
CREATE TABLE CUST_CL (
  CSTCL_ID BIGINT PRIMARY KEY,
  CSTCL_TYP VARCHAR(100),
  CSTCL_TYP_VALUE VARCHAR(100),
  CSTCL_EFCTV_DATE DATE,
  CSTCL_CRUD_VALUE char(1),
  CSTCL_USER_ID VARCHAR(100),
  CSTCL_WS_ID VARCHAR(100),
  CSTCL_PRGM_ID VARCHAR(100),
  CSTCL_HOST_TS TIMESTAMP,
  CSTCL_LOCAL_TS TIMESTAMP,
  CSTCL_ACPT_TS TIMESTAMP,
  CSTCL_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTCL_UUID VARCHAR(100)
);

CREATE TABLE CUST_DETAILS (
  CST_ID BIGINT PRIMARY KEY,
  CSTDET_TYPE BIGINT,
  CSTDET_FULL_NAME VARCHAR(100),
  CSTDET_DOB DATE,
  CSTDET_STATUS VARCHAR(100),
  CSTDET_MOBILE BIGINT UNIQUE,
  CSTDET_EMAIL VARCHAR(100) UNIQUE,
  CSTDET_COUNTRY VARCHAR(100),
  CSTDET_EFCTV_DATE DATE,
  CSTDET_CRUD_VALUE char(1),
  CSTDET_USER_ID VARCHAR(100),
  CSTDET_WS_ID VARCHAR(100),
  CSTDET_PRGM_ID VARCHAR(100),
  CSTDET_HOST_TS TIMESTAMP,
  CSTDET_LOCAL_TS TIMESTAMP,
  CSTDET_ACPT_TS TIMESTAMP,
  CSTDET_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTDET_UUID VARCHAR(100),
  FOREIGN KEY (CSTDET_TYPE) REFERENCES CUST_CL(CSTCL_ID)
);

CREATE TABLE CUST_ID (
  CSTID_IDFR BIGINT PRIMARY KEY,
  CST_ID BIGINT,
  CUSTID_CLS_ID BIGINT,
  CUSTID_VALUE VARCHAR(100) UNIQUE,
  CSTID_EFCTV_DATE DATE,
  CSTID_CRUD_VALUE char(1),
  CSTID_USER_ID VARCHAR(100),
  CSTID_WS_ID VARCHAR(100),
  CSTID_PRGM_ID VARCHAR(100),
  CSTID_HOST_TS TIMESTAMP,
  CSTID_LOCAL_TS TIMESTAMP,
  CSTID_ACPT_TS TIMESTAMP,
  CSTID_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTID_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID)
);

CREATE TABLE CUST_NAME (
  CSTNAME_IDFR BIGINT PRIMARY KEY,
  CST_ID BIGINT,
  CSTNAME_CLS_ID BIGINT,
  CSTNAME_VALUE VARCHAR(100),
  CSTNAME_EFCTV_DATE DATE,
  CSTNAME_CRUD_VALUE char(1),
  CSTNAME_USER_ID VARCHAR(100),
  CSTNAME_WS_ID VARCHAR(100),
  CSTNAME_PRGM_ID VARCHAR(100),
  CSTNAME_HOST_TS TIMESTAMP,
  CSTNAME_LOCAL_TS TIMESTAMP,
  CSTNAME_ACPT_TS TIMESTAMP,
  CSTNAME_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTNAME_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTNAME_CLS_ID) REFERENCES CUST_CL(CSTCL_ID)
);

CREATE TABLE CUST_POI (
  CSTPOI_IDFR BIGINT PRIMARY KEY,
  CST_ID BIGINT,
  CSTPOI_CLS_ID BIGINT,
  CSTPOI_VALUE VARCHAR(100) UNIQUE,
  CSTPOI_START DATE,
  CSTPOI_END DATE,
  CSTPOI_EFCTV_DATE DATE,
  CSTPOI_CRUD_VALUE char(1),
  CSTPOI_USER_ID VARCHAR(100),
  CSTPOI_WS_ID VARCHAR(100),
  CSTPOI_PRGM_ID VARCHAR(100),
  CSTPOI_HOST_TS TIMESTAMP,
  CSTPOI_LOCAL_TS TIMESTAMP,
  CSTPOI_ACPT_TS TIMESTAMP,
  CSTPOI_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTPOI_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTPOI_CLS_ID) REFERENCES CUST_CL(CSTCL_ID)
);

CREATE TABLE CUST_ADDRESS (
  CSTADD_IDFR BIGINT PRIMARY KEY,
  CST_ID BIGINT,
  CSTADD_CLS_ID BIGINT,
  CSTADD_VALUE VARCHAR(100),
  CSTADD_EFCTV_DATE DATE,
  CSTADD_CRUD_VALUE char(1),
  CSTADD_USER_ID VARCHAR(100),
  CSTADD_WS_ID VARCHAR(100),
  CSTADD_PRGM_ID VARCHAR(100),
  CSTADD_HOST_TS TIMESTAMP,
  CSTADD_LOCAL_TS TIMESTAMP,
  CSTADD_ACPT_TS TIMESTAMP,
  CSTADD_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTADD_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTADD_CLS_ID) REFERENCES CUST_CL(CSTCL_ID)
);

CREATE TABLE CUST_SIGNIN (
  CSTSIGN_IDFR BIGINT PRIMARY KEY,
  CST_ID BIGINT,
  CSTSIGN_USRNAME VARCHAR(100) UNIQUE,
  CSTSIGN_PASSWORD VARCHAR(100),
  CSTSIGN_EFCTV_DATE DATE,
  CSTSIGN_CRUD_VALUE char(1),
  CSTSIGN_USER_ID VARCHAR(100),
  CSTSIGN_WS_ID VARCHAR(100),
  CSTSIGN_PRGM_ID VARCHAR(100),
  CSTSIGN_HOST_TS TIMESTAMP,
  CSTSIGN_LOCAL_TS TIMESTAMP,
  CSTSIGN_ACPT_TS TIMESTAMP,
  CSTSIGN_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTSIGN_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID)
);


