

CREATE TABLE CUST_CL (
  CSTCL_ID Number(15) PRIMARY KEY,
  CSTCL_TYP VARCHAR(100),
  CSTCL_TYP_VALUE VARCHAR100),
  CSTCL_EFCTV_DATE DATE,
  CSTCL_CRUD_VALUE char(1),
  CSTCL_USER_ID VARCHAR(100),
  CSTCL_WS_ID VARCHAR(100),
  CSTCL_PRGM_ID VARCHAR(100),
  CSTCL_HOST_TS TIMESTAMP,
  CSTCL_LOCAL_TS TIMESTAMP,
  CSTCL_ACPT_TS TIMESTAMP,
  CSTCL_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTCL_UUID VARCHAR(100)
);

CREATE TABLE CUST_ID (
  CST_ID NUMBER(15) PRIMARY KEY,
  CUSTID_TYPE VARCHAR(100),
  CUSTID_ITEM VARCHAR(100),
  CSTID_EFCTV_DATE DATE,
  CSTID_CRUD_VALUE char(1),
  CSTID_USER_ID VARCHAR(100),
  CSTID_WS_ID VARCHAR(100),
  CSTID_PRGM_ID VARCHAR(100),
  CSTID_HOST_TS TIMESTAMP,
  CSTID_LOCAL_TS TIMESTAMP,
  CSTID_ACPT_TS TIMESTAMP,
  CSTID_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTID_UUID VARCHAR(100)
);

CREATE TABLE CUST_DETAILS (
  CST_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_ID(CST_ID),
  CSTDET_TYPE VARCHAR(100) PRIMARY KEY REFERENCES CUST_CL(CSTCL_ID),
  CSTDET_FULL_NAME VARCHAR(100),
  CSTDET_DOB DATE,
  CSTDET_STATUS VARCHAR(100),
  CSTDET_CONTACT NUMBER(15),
  CSTDET_MOBILE NUMBER(15),
  CSTDET_EMAIL VARCHAR(100),
  CSTDET_COUNTRY VARCHAR(100),
  CSTDET_EFCTV_DATE DATE,
  CSTDET_CRUD_VALUE char(1),
  CSTDET_USER_ID VARCHAR(100),
  CSTDET_WS_ID VARCHAR(100),
  CSTDET_PRGM_ID VARCHAR(100),
  CSTDET_HOST_TS TIMESTAMP,
  CSTDET_LOCAL_TS TIMESTAMP,
  CSTDET_ACPT_TS TIMESTAMP,
  CSTDET_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTDET_UUID VARCHAR(100)
);

CREATE TABLE CUST_NAME (
  CST_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_ID(CST_ID),
  CSTNAME_CLS_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_CL(CSTCL_ID),
  CSTNAME_VALUE VARCHAR(100),
  CSTNAME_EFCTV_DATE DATE,
  CSTNAME_CRUD_VALUE char(1),
  CSTNAME_USER_ID VARCHAR(100),
  CSTNAME_WS_ID VARCHAR(100),
  CSTNAME_PRGM_ID VARCHAR(100),
  CSTNAME_HOST_TS TIMESTAMP,
  CSTNAME_LOCAL_TS TIMESTAMP,
  CSTNAME_ACPT_TS TIMESTAMP,
  CSTNAME_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTNAME_UUID VARCHAR(100)
);

CREATE TABLE CUST_POI (
  CST_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_ID(CST_ID),
  CSTPOI_CLS_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_CL(CSTCL_ID),
  CSTPOI_VALUE VARCHAR(100),
  CSTPOI_START DATE,
  CSTPOI_END DATE,
  CSTPOI_EFCTV_DATE DATE,
  CSTPOI_CRUD_VALUE char(1),
  CSTPOI_USER_ID VARCHAR(100),
  CSTPOI_WS_ID VARCHAR(100),
  CSTPOI_PRGM_ID VARCHAR(100),
  CSTPOI_HOST_TS TIMESTAMP,
  CSTPOI_LOCAL_TS TIMESTAMP,
  CSTPOI_ACPT_TS TIMESTAMP,
  CSTPOI_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTPOI_UUID VARCHAR(100)
);

CREATE TABLE CUST_ADDRESS (
  CST_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_ID(CST_ID),
  CSTADD_CLS_ID NUMBER(15) PRIMARY KEY REFERENCES CUST_CL(CSTCL_ID),
  CSTADD_VALUE undefined,
  CSTADD_EFCTV_DATE DATE,
  CSTADD_CRUD_VALUE char(1),
  CSTADD_USER_ID VARCHAR(100),
  CSTADD_WS_ID VARCHAR(100),
  CSTADD_PRGM_ID VARCHAR(100),
  CSTADD_HOST_TS TIMESTAMP,
  CSTADD_LOCAL_TS TIMESTAMP,
  CSTADD_ACPT_TS TIMESTAMP,
  CSTADD_ACPT_TS_UTC_OFST TIMESTAMP,
  CSTADD_UUID VARCHAR(100)
);
