


CREATE TABLE CUST_CL (
  CSTCL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CSTCL_TYP VARCHAR(100) NOT NULL,
  CSTCL_TYP_VALUE VARCHAR(100) NOT NULL,
  CSTCL_EFCTV_DATE DATE NOT NULL,
  CSTCL_CRUD_VALUE char(1) NOT NULL,
  CSTCL_USER_ID VARCHAR(100) NOT NULL,
  CSTCL_WS_ID VARCHAR(100) NOT NULL,
  CSTCL_PRGM_ID VARCHAR(100) NOT NULL,
  CSTCL_HOST_TS TIMESTAMP NOT NULL,
  CSTCL_LOCAL_TS TIMESTAMP NOT NULL,
  CSTCL_ACPT_TS TIMESTAMP NOT NULL,
  CSTCL_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  CSTCL_UUID VARCHAR(100)
);

CREATE TABLE FIN_INSTITUTIONS(
  INSTITUTION_ID INT AUTO_INCREMENT PRIMARY KEY,
  INSTITUTION_NAME VARCHAR(100) NOT NULL,
  INST_EFCTV_DATE DATE NOT NULL,
  INST_CRUD_VALUE char(1) NOT NULL,
  INST_USER_ID VARCHAR(100) NOT NULL,
  INST_WS_ID VARCHAR(100) NOT NULL,
  INST_PRGM_ID VARCHAR(100) NOT NULL,
  INST_HOST_TS TIMESTAMP NOT NULL,
  INST_LOCAL_TS TIMESTAMP NOT NULL,
  INST_ACPT_TS TIMESTAMP NOT NULL,
  INST_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  INST_UUID VARCHAR(100)
);

CREATE TABLE CUST_DETAILS (
  CSTDET_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTDET_TYPE BIGINT NOT NULL,
  CSTDET_FULL_NAME VARCHAR(100) NOT NULL,
  CSTDET_DOB DATE NOT NULL,
  CSTDET_STATUS VARCHAR(100) NOT NULL,
  CSTDET_MOBILE BIGINT UNIQUE NOT NULL,
  CSTDET_EMAIL VARCHAR(100) UNIQUE NOT NULL,
  CSTDET_COUNTRY VARCHAR(100) NOT NULL,
  CSTDET_EFCTV_DATE DATE NOT NULL,
  CSTDET_CRUD_VALUE char(1) NOT NULL,
  CSTDET_USER_ID VARCHAR(100) NOT NULL,
  CSTDET_WS_ID VARCHAR(100) NOT NULL,
  CSTDET_PRGM_ID VARCHAR(100) NOT NULL,
  CSTDET_HOST_TS TIMESTAMP NOT NULL,
  CSTDET_LOCAL_TS TIMESTAMP NOT NULL,
  CSTDET_ACPT_TS TIMESTAMP NOT NULL,
  CSTDET_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTDET_UUID VARCHAR(100),
  FOREIGN KEY (CSTDET_TYPE) REFERENCES CUST_CL(CSTCL_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);

CREATE TABLE CUST_ID (
  CSTID_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTID_CLS_ID BIGINT NOT NULL,
  CSTID_VALUE VARCHAR(100) UNIQUE NOT NULL,
  CSTID_EFCTV_DATE DATE NOT NULL,
  CSTID_CRUD_VALUE char(1) NOT NULL,
  CSTID_USER_ID VARCHAR(100) NOT NULL,
  CSTID_WS_ID VARCHAR(100) NOT NULL,
  CSTID_PRGM_ID VARCHAR(100) NOT NULL,
  CSTID_HOST_TS TIMESTAMP NOT NULL,
  CSTID_LOCAL_TS TIMESTAMP NOT NULL,
  CSTID_ACPT_TS TIMESTAMP NOT NULL,
  CSTID_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTID_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTID_CLS_ID) REFERENCES CUST_CL(CSTCL_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);

CREATE TABLE CUST_NAME (
  CSTNAME_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTNAME_CLS_ID BIGINT NOT NULL,
  CSTNAME_VALUE VARCHAR(100) NOT NULL,
  CSTNAME_EFCTV_DATE DATE NOT NULL,
  CSTNAME_CRUD_VALUE char(1) NOT NULL,
  CSTNAME_USER_ID VARCHAR(100) NOT NULL,
  CSTNAME_WS_ID VARCHAR(100) NOT NULL,
  CSTNAME_PRGM_ID VARCHAR(100) NOT NULL,
  CSTNAME_HOST_TS TIMESTAMP NOT NULL,
  CSTNAME_LOCAL_TS TIMESTAMP NOT NULL,
  CSTNAME_ACPT_TS TIMESTAMP NOT NULL,
  CSTNAME_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTNAME_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTNAME_CLS_ID) REFERENCES CUST_CL(CSTCL_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);

CREATE TABLE CUST_POI (
  CSTPOI_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTPOI_CLS_ID BIGINT NOT NULL,
  CSTPOI_VALUE VARCHAR(100) UNIQUE NOT NULL,
  CSTPOI_START DATE NOT NULL,
  CSTPOI_END DATE NOT NULL,
  CSTPOI_EFCTV_DATE DATE NOT NULL,
  CSTPOI_CRUD_VALUE char(1) NOT NULL,
  CSTPOI_USER_ID VARCHAR(100) NOT NULL,
  CSTPOI_WS_ID VARCHAR(100) NOT NULL,
  CSTPOI_PRGM_ID VARCHAR(100) NOT NULL,
  CSTPOI_HOST_TS TIMESTAMP NOT NULL,
  CSTPOI_LOCAL_TS TIMESTAMP NOT NULL,
  CSTPOI_ACPT_TS TIMESTAMP NOT NULL,
  CSTPOI_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTPOI_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTPOI_CLS_ID) REFERENCES CUST_CL(CSTCL_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);

CREATE TABLE CUST_ADDRESS (
  CSTADD_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTADD_CLS_ID BIGINT NOT NULL,
  CSTADD_VALUE VARCHAR(100) NOT NULL,
  CSTADD_EFCTV_DATE DATE NOT NULL,
  CSTADD_CRUD_VALUE char(1) NOT NULL,
  CSTADD_USER_ID VARCHAR(100) NOT NULL,
  CSTADD_WS_ID VARCHAR(100) NOT NULL,
  CSTADD_PRGM_ID VARCHAR(100) NOT NULL,
  CSTADD_HOST_TS TIMESTAMP NOT NULL,
  CSTADD_LOCAL_TS TIMESTAMP NOT NULL,
  CSTADD_ACPT_TS TIMESTAMP NOT NULL,
  CSTADD_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTADD_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (CSTADD_CLS_ID) REFERENCES CUST_CL(CSTCL_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);

CREATE TABLE CUST_SIGNIN (
  CSTSIGN_IDFR BIGINT AUTO_INCREMENT PRIMARY KEY,
  CST_ID BIGINT NOT NULL,
  CSTSIGN_USRNAME VARCHAR(100) UNIQUE NOT NULL,
  CSTSIGN_PASSWORD VARCHAR(100) NOT NULL,
  CSTSIGN_ROLE VARCHAR(100) NOT NULL,
  CSTSIGN_EFCTV_DATE DATE NOT NULL,
  CSTSIGN_CRUD_VALUE char(1) NOT NULL,
  CSTSIGN_USER_ID VARCHAR(100) NOT NULL,
  CSTSIGN_WS_ID VARCHAR(100) NOT NULL,
  CSTSIGN_PRGM_ID VARCHAR(100) NOT NULL,
  CSTSIGN_HOST_TS TIMESTAMP NOT NULL,
  CSTSIGN_LOCAL_TS TIMESTAMP NOT NULL,
  CSTSIGN_ACPT_TS TIMESTAMP NOT NULL,
  CSTSIGN_ACPT_TS_UTC_OFST TIMESTAMP NOT NULL,
  LDBID INT NOT NULL,
  CSTSIGN_UUID VARCHAR(100),
  FOREIGN KEY (CST_ID) REFERENCES CUST_DETAILS(CST_ID),
  FOREIGN KEY (LDBID) REFERENCES FIN_INSTITUTIONS(INSTITUTION_ID)
);